name: "dbt_demo_data"
version: "1.0.0"
config-version: 2
profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_demo_data:

    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +database: intermediate
      int_events:
        +schema: int_events
        int_events:
          +materialized: table
      int_orders:
        +schema: int_orders
        int_order_history:
          +materialized: table
        int_order_items:
          +materialized: table
        int_orders:
          +materialized: table
      int_products:
        int_distribution_centers:
          +materialized: table
        int_inventory_items:
          +materialized: table
        int_products:
          +materialized: table

      int_users:
        +schema: int_users
        int_users:
          +materialized: table

    marts:
      +database: marts
      orders:
        +schema: orders
        fct_orders:
          +materialized: table
        dim_order_items:
          +materialized: table
      users:
        +schema: users
        fct_users:
          +materialized: table
      products:
        +schema: products
        dim_products:
          +materialized: table
