name: "dbt_demo_data"
version: "1.0.0"
config-version: 2
profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_demo_data:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +database: intermediate
      +schema: intermediate
      +materialized: table
      int_orders:
        +schema: int_orders

    marts:
      +database: marts
      +materialized: table
      fct_orders:
        +schema: orders
      dim_order_items:
        +schema: orders
      fct_users:
        +schema: users
      dim_products:
        +schema: users
